name: Build and Push Docker Image with Versioning

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Get the Git commit hash or tag
    - name: Get Git commit hash
      id: vars
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    # 4. Build the Docker Image
    - name: Build Docker Image
      run: |
        docker build -t your-dockerhub-username/aioti-web:latest .
        docker build -t your-dockerhub-username/aioti-web:${{ env.COMMIT_HASH }} .

    # 5. Push the Docker Image to Docker Hub (latest and version-specific tags)
    - name: Push Docker Image to Docker Hub
      run: |
        docker push your-dockerhub-username/aioti-web:latest
        docker push your-dockerhub-username/aioti-web:${{ env.COMMIT_HASH }}
